server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql:// *mysql server ip here* :3306/warehouse_manager?useUnicode=true&characterEncoding=utf-8&serveTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ##
    password: ##

Logging:
  level:
    com.example: debug